version: 0.2

env:
  variables:
    APP_NAME: disease-finder-api

phases:
  pre_build:
    commands:
      - set eux
      - aws --version
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - sudo apt-get install git -y
      - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

  build:
    commands:
      - export HEROKU_API_KEY=$(aws aws ssm get-parameter --name "heroku-login-api")
      - heroku login
      - heroku container:login
      - heroku container:push web
      - heroku container:release web

  post_build:
    commands:
      - echo Build completed on `date`