version: 0.2

env:
  variables:
    APP_NAME: disease-finder-api

phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - set eux
      - aws --version
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - npm install -g heroku-cli

  build:
    commands:
      - export HEROKU_API_KEY=$(aws ssm get-parameter --name "heroku-login-api" --region eu-west-1)
      - heroku login
      - heroku container:login
      - heroku container:push web
      - heroku container:release web

  post_build:
    commands:
      - echo Build completed on `date`